### PR TITLE
Olf0 strings de

### PR DESCRIPTION
**Pull request by Olf0**
Rectified German strings: Typos, grammar, phrasing etc.

HTH

### CODE REVIEW

**Comment by JusticeRage** [comment]
Thanks a lot for looking into this! As my German is quite poor, I'm absolutely unable to validate your modifications compared to the previous translations. I think it might be best if you could discuss them with their original author.
The preferred way to translate the app is to register at https://apktrack.oneskyapp.com and use the web interface to submit / comment on the existing strings. Would you be able to port your changes over there, so the initial translator can provide some feedback on them if they wish to do so? Sorry for making you jump through additional hoops there :(

**Comment by Olf0** [comment]
I was able to authenticate myself via oauth at Onskyapp, but this is even bigger crap than the other translation platforms.  Have a permanently spinning thingy there, when trying to access ApkTrack's translations, and Oneskyapp is permanently nagging "Open new project" etc., so the answer is "No, I am not going through these hoops", neither technically or that I am willing to.

See, the German translations were full of typos, partially badly phrased and had one severe cut&paste error (duplicated string in wrong place): In short, they were of inferior quality, creating a bad impression for German ApkTrack users.

I believe you already know my striving for quality well enough, so either accept these enhancements (please!) or deny them, but Oneskyapp is definitely not for me.
(And I guess you already realised that I am a native German speaker, while I am not so sure, if the original translatior is one, as many strings were translated from English quite literally.)

P.S.: Transifex would have been O.K., as I have a local app for editing strings there.

**Comment by JusticeRage** [comment]
Fine, if you really can't work with OneSkyApp, I won't force you. I also find their platform quite clunky. I'm trusting you with the German translation then!

**Comment by Olf0** [comment]
Thank you for both aspects of this (i.e. improving the German translations & trusting me for the quality of them).

**Comment by JusticeRage** [comment]
Don't mention it! I'm the one thanking you for your involvement.
Regarding pull requests, I would advise that you work on the beta branch. This doesn't have much impact, but will make sure that your changes are integrated in the next beta APK - otherwise, they will not be reflected in the app until the next stable release.

It is correct to update the README.md in the master branch (as it's the one displayed on the main page), but translations (or any possible code) should be integrated in the beta channel so that mistakes can be caught early!
Thanks!

**Comment by Olf0** [comment]
Hi Ivan,

On 8 November 2017 03:24:46 CET, Ivan Kwiatkowski <notifications@github.com> wrote:
> Don't mention it! I'm the one thanking you for your involvement.

Well for a good part I am abusing ApkTrack (and you) to learn how to use Git in practice, after reading a lot about its technical background for more than 10 years.  And of course, because I like ApkTrack (that is why I picked it for gaining experience).
Many things still "feel" strange for me as an former CVS and short time SVN user, as one has to think in commits, which have an temporal order (in contrast to files).
And all those practical details, i.e. making "squash commits" and commenting that one properly seems to be the proper way to go.

> Regarding pull requests, I would advise that you work on the beta
> branch. This doesn't have much impact, but will make sure that your
> changes are integrated in the next beta APK - otherwise, they will not
> be reflected in the app until the next stable release.

I see: O.K.
I already mixed my clone ("fork") of your Git repository up to an extent, which forced me to delete it and start anew.

-- 
Cheers,
Olf

**Pull request merged**
