### PR TITLE
Enhanced readme.md

### PR DESCRIPTION
**Pull request by Olf0**
Updated readme.md with ApkTrack's description from F-Droid (originally issue #111) and some other enhancements.  I hope to have carried this out O.K., WRT content *and* using Github / git, as this is my first PR ever.
Cheers & HTH

### CODE REVIEW

**Comment by JusticeRage** [comment]
Looks perfect to me! Thanks a lot!

**Comment by Olf0** [comment]
@JusticeRage: Thanks for merging.

Can you please consider to also replace the single line repository description (currently "An Android application which periodically checks updates for installed apps, on devices without the Play Store.") by hitting the *Edit* button to the right of it (only the repository owner can do that AFAICS) with:

ApkTrack is an Android app, which checks if updates for installed APKs are available. 

This brings the repository description in line with the descriptions in the updated README.md, shortens it and makes it IMO easier to comprehend.

**Comment by Olf0** [comment]
While at it (the single line description), you may also add some items to the *Topic* line below. 
Although not really relevant, adding appropriate topic items seems to be a good practice.  For basic information about Github *Topics*, see [About Topics](https://help.github.com/articles/about-topics/) and the Github blog entry [Introducing Topics](https://github.com/blog/2309-introducing-topics). 

Looking at the [available topic items](https://github.com/github/explore/tree/master/topics), IMO there are just two-and-a-half relevant ones for ApkTrack:

* [android](https://github.com/github/explore/blob/master/topics/android/index.md) or its aliases android-application, android-app
* [java](https://github.com/github/explore/blob/master/topics/java/index.md)
* And maybe [bot](https://github.com/github/explore/blob/master/topics/bot/index.md)

Without much pondering about that much (which would probably not be worth it, anyway), I would pick **android** *and* **android-application** (even though they resolve to the same topic item "android", because that combination describes ApkTrack better, being a tool for Android as such *and* an Android application), plus **java**; not sure about **bot** though, but basically it indicates some aspects of ApkTrack's functionality correctly, so setting it as well does do no harm.
But as ApkTrack is your baby and everybody's mileage varies, consider these just as some spontaneous thoughts on this Github Topics topic.

**Edit:** I just tried this (and as a suggestion for an order of these topic items): https://github.com/Olf0/ApkTrack

**Comment by JusticeRage** [comment]
Thanks for the suggestion! I've edited the repository's description and tags as per your recommendation.
I left out the **bot** tag, as I feel like this doesn't really fit what ApkTrack does, replacing it with "scraping websites" and adding "apk" instead.

**Comment by Olf0** [comment]
Looking really good, and your topic tag selection (did not find these) is clearly better than my suggestion.
Thanks.

**Pull request merged**
