### PR TITLE
lots of maintenance

### PR DESCRIPTION
**Pull request by TacoTheDank**
- update android studio to 3.2.1
- updated gradle to 4.10.2
- target pie
- dependency updates
- java 1.8 compatibility, and code changes to go with it (lambdas, etc)
- reformatted code
- changed ApplicationTest to use junit and runner stuff

### CODE REVIEW

**Comment by JusticeRage** [comment]
Hey!
Thanks a lot for this pull request. Have you verified that the updated code works with Android Pie? Based on my testing, Pie has made significant changes to some permissions used by ApkTrack. They break, in particular, ApkTrack's ability to detect when an application is updated.
Please let me know if the application is still working properly for you on a Pie device :)

**Comment by TacoTheDank** [comment]
i havent tested... ill set it to target oreo then, since i dont have a pie device >.>

also i forgot to change the travis sys img to arm64 lol, thats why it failed on the previous commit

**Comment by JusticeRage** [comment]
Please test the app on Oreo as well on your device - in particular the case that I described above (updating an app and seeing if it is correctly taken into account in ApkTrack). It's possible that the problem is present in this OS revision as well.

**Comment by TacoTheDank** [comment]
Closing, as this app can be replaced with https://github.com/hemker/apkgrabber

**Pull request closed without merging**
